<?php 

    $creature_type = $_POST['creature_type'];    

    if (!empty ($_POST['creature_type'])) {
        $creature_type = $_POST ['creature_type'];
    } else {  
        $creature_type = 'NOTHING!';
    } 

    

    if (!empty ($_POST['name'])) {
        $name = $_POST['name'];
        $name = strtolower ($name);
        $name = ucwords ($name);
        $name = htmlspecialchars ($name);
        $name = strip_tags ($name);
    } else {
        $name = 'no one';
    }


    
?>


<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Creature Generator</title>
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/uniform.default.css">
<link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="holder">
<a id="the_return_button" href="step_one.php"><button>RETURN</button></a>

<h1 id="the_title">You have been made into <?php echo $creature_type ?></h1>



    <p>Thanks <span id="nam3"><?php  echo $name; ?>,</span><br><br>Today is <?php echo date("l F jS Y"); ?> (just so you know), <br><br><br> Your creature self has been generated by the computer. No one can predict the results. It is ready and for you to see if you dare. Take a look at your creature self by clicking on the <button id="bada_bing" name="badabing" id="badabing">BADA-BING</button> button.</p>

<div id="results">

<?php 
    
    $aliens_array = array('Alien Komodo! The results are not pretty, but not everyone is lucky.', 'Bob from pluto! You look wonderful. You are out of this world.', 'Joey Jenetta! Well, you look pretty much the same, and humans will probably look like this at some point.', 'Hobo Alien. You had a smelly genetic makeover.');

    $robots_array = array('Bender! This robot is very well designed. You are lucky and classy.', ' Classic robot! You are SOO00oo classic!', 'Wall-e! You are the future and you are quite humble.', 'R2-D2! Well, you wont be human but you will always be clever.');
    
    $alien_img = '<br>' . '<img src="images/alien.png" width="237" height="342" alt="alien">' . '<br>';
    $robot_img = '<br>' . '<img src="images/robot.png" width="283.5" height="274.5" alt="robot">' . '<br>';


    $alien_result = $alien_img . $aliens_array [mt_rand (0, 3)];
    $robot_result = $robot_img . $robots_array [mt_rand (0, 3)]; 


    if ($creature_type == 'an alien') {
        echo $alien_result;
}   if ($creature_type == 'a robot') {
         echo $robot_result;
} 
    
?>

</div>

</div>

<script>
	$("#maker_results").hide();
	$(document).ready(function () {
    
    $("#click").click(function (e) {
        e.preventDefault();
        
		 $("#maker_results").slideDown(500);
        
    });

}); //ready

</script>

<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="js/jquery.uniform.min.js"></script>
<script>
jQuery("select, input:checkbox, input:radio, input:file, input:text, input:submit, textarea").uniform();
</script>
</body>
</html>
